#!/usr/bin/env node
// Regenerates content/llms.txt (curated, AI-navigable index) and
// content/llms-full.txt (the whole corpus concatenated, one plain-text file).
//
// Why static files and not a Quartz emitter: keeping these out of the Vercel
// build command means a generator bug can never break a production deploy.
// The cost is that they are a SNAPSHOT — re-run this before deploying when
// content changes:  node scripts/gen-llms.mjs
//
// It emits NO guessed per-entry URLs. The authoritative per-entry URL list is
// /sitemap.xml (already generated by Quartz). llms.txt links only the 19 domain
// hub pages, whose slugs contain no spaces and are therefore safe.

import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, "..")
const CONTENT = path.join(ROOT, "content")
const BASE = "https://ecclesia.lumensyntax.com"
const TODAY = new Date().toISOString().slice(0, 10)

// Top-level files that are not catalogue entries.
const SKIP_TOP = new Set(["index.md", "ENTRY-TEMPLATE.md", "META-PATTERNS.md"])
const HUB = "00-Index.md"

function splitFrontmatter(md) {
  const m = md.match(/^---\n([\s\S]*?)\n---\n?/)
  if (!m) return { fm: {}, body: md }
  const fm = {}
  for (const line of m[1].split("\n")) {
    const mm = line.match(/^([A-Za-z0-9_]+):\s*(.+)$/)
    if (mm) fm[mm[1]] = mm[2].trim()
  }
  return { fm, body: md.slice(m[0].length).replace(/^\s+/, "") }
}

function titleOf(body, fallback) {
  const m = body.match(/^#\s+(.+)$/m)
  return m ? m[1].trim() : fallback
}

// domains = immediate subdirectories of content/
const domains = fs
  .readdirSync(CONTENT, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort()

const model = [] // [{ dom, hub: bool, entries: [{ rel, title, fm, body }] }]
let entryCount = 0

for (const dom of domains) {
  const dir = path.join(CONTENT, dom)
  const files = fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(".md"))
    .sort()
  const hasHub = files.includes(HUB)
  const entries = []
  for (const f of files) {
    if (f === HUB) continue
    const rel = `${dom}/${f}`
    const raw = fs.readFileSync(path.join(dir, f), "utf8")
    const { fm, body } = splitFrontmatter(raw)
    entries.push({ rel, title: titleOf(body, f.replace(/\.md$/, "")), fm, body })
  }
  entryCount += entries.length
  model.push({ dom, hub: hasHub, entries })
}

// ---- llms.txt (curated) -------------------------------------------------
const L = []
L.push("# The Ecclesia")
L.push("")
L.push(
  "> ἐκκλησία — the called out, the assembly. A cross-domain catalogue that maps established findings — from physics to theology, from immunology to economics — to five recurring structural properties: alignment, proportion, honesty, humility, non-fabrication. Every entry cites an established source and marks what is established apart from what is interpreted. CC BY-SA 4.0.",
)
L.push("")
L.push(
  `The full corpus as one file: [/llms-full.txt](${BASE}/llms-full.txt). Every canonical page URL: [/sitemap.xml](${BASE}/sitemap.xml). Source and contribution rules: [github.com/lumensyntax-org/ecclesia](https://github.com/lumensyntax-org/ecclesia).`,
)
L.push("")
L.push(`This index lists ${entryCount} entries across ${domains.length} domains (generated ${TODAY}).`)
L.push("")
L.push("## Domains")
for (const { dom, hub, entries } of model) {
  const hubLink = hub ? ` — [index](${BASE}/${dom}/00-Index)` : ""
  L.push("")
  L.push(`### ${dom}${hubLink}`)
  for (const e of entries) L.push(`- ${e.title}`)
}
L.push("")
L.push("## Meta")
L.push(`- [Home](${BASE}/) — how to read the catalogue`)
L.push(`- [META-PATTERNS](${BASE}/META-PATTERNS) — cross-domain structural invariants, with strength ratings`)
L.push("")
const llmsTxt = L.join("\n")
fs.writeFileSync(path.join(CONTENT, "llms.txt"), llmsTxt)

// ---- llms-full.txt (whole corpus) --------------------------------------
const F = []
F.push("# The Ecclesia — full text export")
F.push("")
F.push(`Generated: ${TODAY}`)
F.push(`Entries: ${entryCount} across ${domains.length} domains (plus ${domains.length} domain-index pages and the META-PATTERNS map, not included below).`)
F.push(`Source: https://github.com/lumensyntax-org/ecclesia`)
F.push(`License: CC BY-SA 4.0`)
F.push(
  `Canonical per-entry URL = ${BASE}/ + the Source path with the .md removed and spaces replaced by hyphens; the authoritative list is ${BASE}/sitemap.xml.`,
)
F.push("")
F.push(
  "This is a point-in-time snapshot for whole-corpus analysis. It is regenerated by scripts/gen-llms.mjs; if the date above is stale, re-run it against the live repo.",
)
F.push("")
for (const { dom, entries } of model) {
  F.push("")
  F.push(`================================================================`)
  F.push(`DOMAIN: ${dom}`)
  F.push(`================================================================`)
  for (const e of entries) {
    const meta = [e.fm.domain && `domain: ${e.fm.domain}`, e.fm.strength && `strength: ${e.fm.strength}`, e.fm.status && `status: ${e.fm.status}`]
      .filter(Boolean)
      .join(" · ")
    F.push("")
    F.push(`## ${e.title}`)
    F.push(`Source: content/${e.rel}${meta ? `  [${meta}]` : ""}`)
    F.push("")
    F.push(e.body.trimEnd())
  }
}
F.push("")
const llmsFull = F.join("\n")
fs.writeFileSync(path.join(CONTENT, "llms-full.txt"), llmsFull)

// ---- report -------------------------------------------------------------
console.log(`llms.txt      ${llmsTxt.length.toLocaleString()} bytes, ${entryCount} entries, ${domains.length} domains`)
console.log(`llms-full.txt ${llmsFull.length.toLocaleString()} bytes`)
