#!/usr/bin/env node
// Regenerates content/llms.txt (curated, AI-navigable index) and
// content/llms-full.txt (the whole corpus concatenated, one plain-text file).
//
// WIRED INTO THE BUILD: vercel.json runs `node scripts/gen-llms.mjs && npx quartz
// build`, so these files are regenerated fresh on every deploy — a new entry or
// domain appears automatically, like the sitemap. The committed copies are only a
// fallback: this script is FAIL-SAFE — on any error it logs and exits 0, leaving
// the existing files in place, so a generator bug can never break a deploy.
//
// It emits NO guessed per-entry URLs. The authoritative per-entry URL list is
// /sitemap.xml (already generated by Quartz). llms.txt links only the 19 domain
// hub pages, whose slugs contain no spaces and are therefore safe.

import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

try {
  const __dirname = path.dirname(fileURLToPath(import.meta.url))
  const ROOT = path.resolve(__dirname, "..")
  const CONTENT = path.join(ROOT, "content")
  const BASE = "https://ecclesia.lumensyntax.com"
  const TODAY = new Date().toISOString().slice(0, 10)

  // Top-level files that are not catalogue entries.
  const HUB = "00-Index.md"

  const splitFrontmatter = (md) => {
    const m = md.match(/^---\n([\s\S]*?)\n---\n?/)
    if (!m) return { fm: {}, body: md }
    const fm = {}
    for (const line of m[1].split("\n")) {
      const mm = line.match(/^([A-Za-z0-9_]+):\s*(.+)$/)
      if (mm) fm[mm[1]] = mm[2].trim()
    }
    return { fm, body: md.slice(m[0].length).replace(/^\s+/, "") }
  }

  const titleOf = (body, fallback) => {
    const m = body.match(/^#\s+(.+)$/m)
    return m ? m[1].trim() : fallback
  }

  // domains = immediate subdirectories of content/
  const domains = fs
    .readdirSync(CONTENT, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort()

  const model = [] // [{ dom, hub: bool, entries: [{ rel, title, fm, body }] }]
  let entryCount = 0

  for (const dom of domains) {
    const dir = path.join(CONTENT, dom)
    const files = fs
      .readdirSync(dir)
      .filter((f) => f.endsWith(".md"))
      .sort()
    const hasHub = files.includes(HUB)
    const entries = []
    for (const f of files) {
      if (f === HUB) continue
      const rel = `${dom}/${f}`
      const raw = fs.readFileSync(path.join(dir, f), "utf8")
      const { fm, body } = splitFrontmatter(raw)
      entries.push({ rel, title: titleOf(body, f.replace(/\.md$/, "")), fm, body })
    }
    entryCount += entries.length
    model.push({ dom, hub: hasHub, entries })
  }

  // ---- llms.txt (curated) -----------------------------------------------
  const L = []
  L.push("# The Ecclesia")
  L.push("")
  L.push(
    "> ἐκκλησία — the called out, the assembly. A cross-domain catalogue that maps established findings — from physics to theology, from immunology to economics — to five recurring structural properties: alignment, proportion, honesty, humility, non-fabrication. Every entry cites an established source and marks what is established apart from what is interpreted. CC BY-SA 4.0.",
  )
  L.push("")
  L.push(
    `The full corpus as one file: [/llms-full.txt](${BASE}/llms-full.txt). Every canonical page URL: [/sitemap.xml](${BASE}/sitemap.xml). Source and contribution rules: [github.com/lumensyntax-org/ecclesia](https://github.com/lumensyntax-org/ecclesia).`,
  )
  L.push("")
  L.push(`This index lists ${entryCount} entries across ${domains.length} domains (generated ${TODAY}).`)
  L.push("")
  L.push("## Domains")
  for (const { dom, hub, entries } of model) {
    const hubLink = hub ? ` — [index](${BASE}/${dom}/00-Index)` : ""
    L.push("")
    L.push(`### ${dom}${hubLink}`)
    for (const e of entries) L.push(`- ${e.title}`)
  }
  L.push("")
  L.push("## Meta")
  L.push(`- [Home](${BASE}/) — how to read the catalogue`)
  L.push(`- [META-PATTERNS](${BASE}/META-PATTERNS) — cross-domain structural invariants, with strength ratings`)
  L.push("")
  const llmsTxt = L.join("\n")
  fs.writeFileSync(path.join(CONTENT, "llms.txt"), llmsTxt)

  // ---- llms-full.txt (whole corpus) -------------------------------------
  const F = []
  F.push("# The Ecclesia — full text export")
  F.push("")
  F.push(`Generated: ${TODAY}`)
  F.push(`Entries: ${entryCount} across ${domains.length} domains (plus ${domains.length} domain-index pages and the META-PATTERNS map, not included below).`)
  F.push(`Source: https://github.com/lumensyntax-org/ecclesia`)
  F.push(`License: CC BY-SA 4.0`)
  F.push(
    `Canonical per-entry URL = ${BASE}/ + the Source path with the .md removed and spaces replaced by hyphens; the authoritative list is ${BASE}/sitemap.xml.`,
  )
  F.push("")
  F.push(
    "This is a point-in-time snapshot for whole-corpus analysis. It is regenerated by scripts/gen-llms.mjs on every deploy.",
  )
  F.push("")
  for (const { dom, entries } of model) {
    F.push("")
    F.push(`================================================================`)
    F.push(`DOMAIN: ${dom}`)
    F.push(`================================================================`)
    for (const e of entries) {
      const meta = [e.fm.domain && `domain: ${e.fm.domain}`, e.fm.strength && `strength: ${e.fm.strength}`, e.fm.status && `status: ${e.fm.status}`]
        .filter(Boolean)
        .join(" · ")
      F.push("")
      F.push(`## ${e.title}`)
      F.push(`Source: content/${e.rel}${meta ? `  [${meta}]` : ""}`)
      F.push("")
      F.push(e.body.trimEnd())
    }
  }
  F.push("")
  const llmsFull = F.join("\n")
  fs.writeFileSync(path.join(CONTENT, "llms-full.txt"), llmsFull)

  console.log(`[gen-llms] llms.txt ${llmsTxt.length.toLocaleString()} bytes, ${entryCount} entries, ${domains.length} domains`)
  console.log(`[gen-llms] llms-full.txt ${llmsFull.length.toLocaleString()} bytes`)
} catch (e) {
  // FAIL-SAFE: never break the build. Keep whatever llms files are committed.
  console.error("[gen-llms] generation failed; keeping existing llms files:", e?.message ?? e)
  process.exit(0)
}
