#!/usr/bin/env node
// Regenerates content/llms.txt (curated, AI-navigable index) and
// content/llms-full.txt (the whole corpus concatenated, one plain-text file).
//
// WIRED INTO THE BUILD: vercel.json runs `node scripts/gen-llms.mjs && npx quartz
// build`, so these files are regenerated fresh on every deploy.
//
// Publication rules mirror Quartz (scripts/gen-llms-lib.mjs, unit-tested): it
// skips drafts (RemoveDrafts), the ignored directories (ignorePatterns), and the
// navigation indexes / template / meta-patterns map, and it recurses into
// sub-folders. Frontmatter parsing is CRLF-tolerant.
//
// FAIL-VISIBLE: on any error it exits NON-ZERO, which (via the `&&`) fails the
// build so a stale or half-written pair is never promoted. Vercel keeps the
// previous, consistent deploy when a build fails. Both outputs are built fully in
// memory before either is written, so a parse/logic error fails before any write.
//
// It emits NO guessed per-entry URLs; the authoritative per-entry URL list is
// /sitemap.xml (generated by Quartz). Each entry carries its repo Source path for
// provenance only.

import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { parseFrontmatter, isIndexOrTemplate, isDraft, IGNORED_DIRS } from "./gen-llms-lib.mjs"

function main() {
  const __dirname = path.dirname(fileURLToPath(import.meta.url))
  const ROOT = path.resolve(__dirname, "..")
  const CONTENT = path.join(ROOT, "content")
  const BASE = "https://ecclesia.lumensyntax.com"
  const TODAY = new Date().toISOString().slice(0, 10)

  const titleOf = (body, fallback) => {
    const m = body.match(/^#\s+(.+)$/m)
    return m ? m[1].trim() : fallback
  }

  // Recursively collect publishable entry files under a domain directory.
  const collect = (absDir, relDir) => {
    const out = []
    for (const d of fs.readdirSync(absDir, { withFileTypes: true })) {
      if (d.isDirectory()) {
        if (IGNORED_DIRS.includes(d.name)) continue
        out.push(...collect(path.join(absDir, d.name), `${relDir}/${d.name}`))
      } else if (d.name.endsWith(".md") && !isIndexOrTemplate(d.name)) {
        const raw = fs.readFileSync(path.join(absDir, d.name), "utf8")
        const { fm, body } = parseFrontmatter(raw)
        if (isDraft(fm)) continue // mirror Quartz RemoveDrafts
        out.push({
          rel: `${relDir}/${d.name}`,
          title: titleOf(body, d.name.replace(/\.md$/, "")),
          fm,
          body,
        })
      }
    }
    return out
  }

  const domains = fs
    .readdirSync(CONTENT, { withFileTypes: true })
    .filter((d) => d.isDirectory() && !IGNORED_DIRS.includes(d.name))
    .map((d) => d.name)
    .sort()

  const model = []
  let entryCount = 0
  for (const dom of domains) {
    const dir = path.join(CONTENT, dom)
    const hasHub = fs.existsSync(path.join(dir, "00-Index.md"))
    const entries = collect(dir, dom).sort((a, b) => a.rel.localeCompare(b.rel))
    entryCount += entries.length
    model.push({ dom, hub: hasHub, entries })
  }

  // ---- llms.txt (curated) -----------------------------------------------
  const L = []
  L.push("# The Ecclesia")
  L.push("")
  L.push(
    "> ἐκκλησία — the called out, the assembly. A cross-domain catalogue that maps established findings — from physics to theology, from immunology to economics — to five recurring structural properties: alignment, proportion, honesty, humility, non-fabrication. Every entry cites an established source and marks what is established apart from what is interpreted. CC BY-SA 4.0.",
  )
  L.push("")
  L.push(
    `The full corpus as one file: [/llms-full.txt](${BASE}/llms-full.txt). Every canonical page URL: [/sitemap.xml](${BASE}/sitemap.xml). Source and contribution rules: [github.com/lumensyntax-org/ecclesia](https://github.com/lumensyntax-org/ecclesia).`,
  )
  L.push("")
  L.push(`This index lists ${entryCount} entries across ${domains.length} domains (generated ${TODAY}).`)
  L.push("")
  L.push("## Domains")
  for (const { dom, hub, entries } of model) {
    const hubLink = hub ? ` — [index](${BASE}/${dom}/00-Index)` : ""
    L.push("")
    L.push(`### ${dom}${hubLink}`)
    for (const e of entries) L.push(`- ${e.title}`)
  }
  L.push("")
  L.push("## Meta")
  L.push(`- [Home](${BASE}/) — how to read the catalogue`)
  L.push(`- [META-PATTERNS](${BASE}/META-PATTERNS) — cross-domain structural invariants, with strength ratings`)
  L.push("")
  const llmsTxt = L.join("\n")

  // ---- llms-full.txt (whole corpus) -------------------------------------
  const F = []
  F.push("# The Ecclesia — full text export")
  F.push("")
  F.push(`Generated: ${TODAY}`)
  F.push(
    `Entries: ${entryCount} across ${domains.length} domains (domain-index pages and the META-PATTERNS map are not included below).`,
  )
  F.push(`Source: https://github.com/lumensyntax-org/ecclesia`)
  F.push(`License: CC BY-SA 4.0`)
  F.push(
    `Every canonical per-entry URL is listed at ${BASE}/sitemap.xml. Each entry below carries its repository Source path for provenance only (not a URL).`,
  )
  F.push("")
  F.push(
    "This is a point-in-time snapshot for whole-corpus analysis. It is regenerated by scripts/gen-llms.mjs on every deploy.",
  )
  F.push("")
  for (const { dom, entries } of model) {
    F.push("")
    F.push(`================================================================`)
    F.push(`DOMAIN: ${dom}`)
    F.push(`================================================================`)
    for (const e of entries) {
      const meta = [
        e.fm.domain && `domain: ${e.fm.domain}`,
        e.fm.strength && `strength: ${e.fm.strength}`,
        e.fm.status && `status: ${e.fm.status}`,
      ]
        .filter(Boolean)
        .join(" · ")
      F.push("")
      F.push(`## ${e.title}`)
      F.push(`Source: content/${e.rel}${meta ? `  [${meta}]` : ""}`)
      F.push("")
      F.push(e.body.trimEnd())
    }
  }
  F.push("")
  const llmsFull = F.join("\n")

  // ---- write both (only after both are built) ---------------------------
  fs.writeFileSync(path.join(CONTENT, "llms.txt"), llmsTxt)
  fs.writeFileSync(path.join(CONTENT, "llms-full.txt"), llmsFull)

  console.log(
    `[gen-llms] llms.txt ${llmsTxt.length.toLocaleString()} bytes, ${entryCount} entries, ${domains.length} domains`,
  )
  console.log(`[gen-llms] llms-full.txt ${llmsFull.length.toLocaleString()} bytes`)
}

try {
  main()
} catch (e) {
  // FAIL VISIBLE (T02): fail the build rather than exit 0 and ship a stale or
  // half-written pair. Vercel keeps the previous consistent deploy on a failed build.
  console.error("[gen-llms] generation FAILED (failing the build):", e?.stack ?? e)
  process.exit(1)
}
